version: "3.7"

# TODO attach volume for db on release
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ENVIRONMENT=production
        - PORT=5000
    ports:
      - 5000:5000
