"""empty message

Revision ID: bffdb084111b
Revises: 3939e26ccd10
Create Date: 2019-10-05 17:12:56.379702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffdb084111b'
down_revision = '3939e26ccd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token')
    # ### end Alembic commands ###
